#!/usr/bin/env ruby

LKP_SRC = ENV['LKP_SRC'] || File.dirname(File.dirname(File.dirname(File.realpath($PROGRAM_NAME))))

require "#{LKP_SRC}/lib/statistics"

$stdin.each_line do |line|
  case line
  when /calls per second/
    puts "nanosleep_calls_per_sec: #{line.split[0]}"
  end
end
